// string constants
const
OBJECT                = "Object",
ARRAY                 = "Array",
SET                   = "Set",
MAP                   = "Map",	
FUNCTION              = "Function",
CONVENTION_CONSTANT   = "conventionForConstant",
CONVENTION_PRIVATE    = "conventionForPrivate",
DEFINITION            = "definition",
ASSERTIONS            = "assertions",
ON_FAIL               = "_onFail",
VALIDATE              = "validate",
VALIDATOR             = "_validator",
TEST                  = "test",
EXTEND                = "extend",
EXPECTED              = "expected",
RECEIVED              = "received",
PATH                  = "path",
MESSAGE               = "message",
ERROR_STACK           = "errorStack",
ERROR_COLLECTOR       = "errorCollector",
UNSTACK_ERRORS        = "unstackErrors",
PROTO                 = "prototype",
CONSTRUCTOR           = "constructor",	
DEFAULT               = "default",
DEFAULTS              = "defaults",
RETURN                = "return",
ARGS                  = "arguments",

ARRAY_MUTATOR_METHODS = ["pop", "push", "reverse", "shift", "sort", "splice", "unshift"],
SET_MUTATOR_METHODS   = ["add", "delete", "clear"],	
MAP_MUTATOR_METHODS   = ["set", "delete", "clear"],

STACKTRACE_BLACKBOX_MATCHER = /\n.*object-model(.|\n)*object-model.*/